version: "{build}"
image: Visual Studio 2017
platform: x64

clone_folder: C:\projects\cquery

install:
  - git submodule update --init

build_script:
  - cd C:\projects\cquery
  - python waf configure --msvc_version="msvc 14.0" --msvc_targets=x64
  - python waf build
  - ps: |
      $dir = "cquery-${env:appveyor_build_version}-win64"
      cd C:\projects\cquery
      mkdir "${dir}"
      mkdir "${dir}\build"
      mkdir "${dir}\build\release"
      mkdir "${dir}\build\release\bin"
      copy "build\release\bin\*" "${dir}\build\release\bin"
      copy -recurse "clang_resource_dir" "${dir}\clang_resource_dir"
      7z a -tzip "C:\projects\cquery\${dir}.zip" "${dir}"

artifacts:
  - path: 'cquery-*.zip'

cache:
  - C:\projects\cquery\build\LLVM-4.0.0-win64.exe
  - C:\projects\cquery\build\LLVM-5.0.0-win64.exe
  - C:\projects\cquery\build\LLVM-4.0.0-win64\
  - C:\projects\cquery\build\LLVM-5.0.0-win64\
